"use client";

import { createContext, useContext, useSyncExternalStore, useCallback, type ReactNode } from "react";

export type Locale = "fr" | "en";

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const translations: Record<Locale, Record<string, string>> = {
  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.projects": "Projets",
    "nav.about": "A propos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.cta": "Démarrer un projet",
    "nav.menu": "Menu",

    // Hero
    "hero.badge": "Agence digitale innovante",
    "hero.titleLine1": "Nous donnons vie à vos",
    "hero.titleHighlight": "projets digitaux",
    "hero.titleLine2": "avec exigence.",
    "hero.subtitle": "Développement, recherche et formation — trois expertises au service de votre ambition digitale.",
    "hero.cta1": "Démarrer un projet",
    "hero.cta2": "Découvrir nos services",

    // Services - Departments
    "services.badge": "Nos départements",
    "services.title": "Trois pôles d'expertise",
    "services.titleHighlight": "au service de votre vision",
    "services.subtitle": "Notre entreprise est structurée autour de trois départements complémentaires pour répondre à tous vos besoins digitaux.",

    "services.dev.title": "Département Développement",
    "services.dev.desc": "Conception et réalisation de solutions digitales sur mesure, du site vitrine aux logiciels complexes.",
    "services.dev.tag": "Développement",
    "services.dev.item1": "Sites web vitrine & e-commerce",
    "services.dev.item2": "Applications web & mobiles",
    "services.dev.item3": "Logiciels métier sur mesure",
    "services.dev.item4": "API & intégrations",

    "services.research.title": "Département Recherches Innovantes",
    "services.research.desc": "Exploration de technologies émergentes et développement de solutions d'avant-garde pour anticiper les besoins de demain.",
    "services.research.tag": "R&D",
    "services.research.item1": "Intelligence artificielle & IA générative",
    "services.research.item2": "Automatisation intelligente",
    "services.research.item3": "Blockchain & Web3",
    "services.research.item4": "IoT & systèmes embarqués",

    "services.training.title": "Département Formations",
    "services.training.desc": "Programmes de formation professionnelle pour accompagner la montée en compétences de vos équipes sur les technologies modernes.",
    "services.training.tag": "Formation",
    "services.training.item1": "Développement web & mobile",
    "services.training.item2": "Data Science & IA",
    "services.training.item3": "DevOps & Cloud",
    "services.training.item4": "Workshops & coaching technique",

    "services.cta.text": "Vous avez un projet en tête ?",
    "services.cta.sub": "Parlons-en et construisons ensemble la solution adaptée à vos ambitions.",
    "services.cta.button": "Discutons de votre projet",

    // Department Pages - Shared
    "dept.backHome": "Retour à l'accueil",
    "dept.currentProjects": "Projets en cours",
    "dept.completedProjects": "Projets réalisés",
    "dept.inProgress": "En cours",
    "dept.completed": "Terminé",
    "dept.teamExpertise": "Expertise de l'équipe",
    "dept.learnMore": "En savoir plus",
    "dept.overview": "Vue d'ensemble",

    // Department Pages - Dev
    "dept.dev.hero.badge": "Département Développement",
    "dept.dev.hero.title": "Des solutions digitales",
    "dept.dev.hero.titleHighlight": "sur mesure",
    "dept.dev.hero.subtitle": "Nous concevons et développons des sites web, applications mobiles et logiciels personnalisés qui propulsent votre activité.",
    "dept.dev.overview.badge": "Notre approche",
    "dept.dev.overview.title": "L'excellence technique",
    "dept.dev.overview.titleHighlight": "au cœur de chaque projet",
    "dept.dev.overview.text1": "Notre département développement réunit des experts passionnés par la création de solutions digitales performantes. Du site vitrine à l'application métier complexe, nous maîtrisons l'ensemble de la chaîne de production.",
    "dept.dev.overview.text2": "Nous adoptons les méthodologies agiles et les technologies les plus récentes pour garantir des livrables de qualité, maintenables et évolutifs.",
    "dept.dev.overview.stat1.value": "150+",
    "dept.dev.overview.stat1.label": "Projets livrés",
    "dept.dev.overview.stat2.value": "98%",
    "dept.dev.overview.stat2.label": "Clients satisfaits",
    "dept.dev.overview.stat3.value": "12",
    "dept.dev.overview.stat3.label": "Développeurs seniors",
    "dept.dev.services.badge": "Nos services",
    "dept.dev.services.title": "Solutions de développement",
    "dept.dev.services.titleHighlight": "complètes",
    "dept.dev.services.s1.title": "Sites Web Vitrine",
    "dept.dev.services.s1.desc": "Sites modernes, responsifs et optimisés SEO pour renforcer votre présence en ligne et attirer de nouveaux clients.",
    "dept.dev.services.s2.title": "E-Commerce",
    "dept.dev.services.s2.desc": "Boutiques en ligne performantes avec gestion des stocks, paiements sécurisés et expérience d'achat optimisée.",
    "dept.dev.services.s3.title": "Applications Web",
    "dept.dev.services.s3.desc": "Applications web sur mesure avec interfaces intuitives, tableaux de bord et fonctionnalités métier avancées.",
    "dept.dev.services.s4.title": "Applications Mobiles",
    "dept.dev.services.s4.desc": "Applications iOS et Android natives ou cross-platform pour toucher vos utilisateurs où qu'ils soient.",
    "dept.dev.services.s5.title": "Logiciels Sur Mesure",
    "dept.dev.services.s5.desc": "Développement de logiciels métier personnalisés pour automatiser et optimiser vos processus internes.",
    "dept.dev.services.s6.title": "API & Intégrations",
    "dept.dev.services.s6.desc": "Conception d'API robustes et intégration de services tiers pour connecter vos systèmes entre eux.",
    "dept.dev.projects.badge": "Nos réalisations",
    "dept.dev.projects.title": "Projets de",
    "dept.dev.projects.titleHighlight": "développement",
    "dept.dev.projects.current.p1.title": "Portail Client NeoBank",
    "dept.dev.projects.current.p1.desc": "Plateforme bancaire en ligne avec tableau de bord interactif, gestion multi-comptes et notifications en temps réel.",
    "dept.dev.projects.current.p1.tag": "Application Web",
    "dept.dev.projects.current.p2.title": "App Mobile FitTrack",
    "dept.dev.projects.current.p2.desc": "Application de suivi sportif avec plans d'entraînement personnalisés, statistiques et intégration d'objets connectés.",
    "dept.dev.projects.current.p2.tag": "Mobile",
    "dept.dev.projects.completed.p1.title": "Marketplace ArtisanConnect",
    "dept.dev.projects.completed.p1.desc": "Place de marché mettant en relation artisans locaux et clients, avec système de réservation et paiement intégré.",
    "dept.dev.projects.completed.p1.date": "Janvier 2026",
    "dept.dev.projects.completed.p2.title": "ERP LogiFlow",
    "dept.dev.projects.completed.p2.desc": "Logiciel de gestion intégré pour PME couvrant la facturation, les stocks et la relation client.",
    "dept.dev.projects.completed.p2.date": "Novembre 2025",
    "dept.dev.projects.completed.p3.title": "Site E-Commerce GreenLeaf",
    "dept.dev.projects.completed.p3.desc": "Boutique en ligne de produits bio avec configurateur de paniers, abonnements et livraison programmée.",
    "dept.dev.projects.completed.p3.date": "Septembre 2025",
    "dept.dev.team.badge": "Notre équipe",
    "dept.dev.team.title": "Les experts",
    "dept.dev.team.titleHighlight": "développement",
    "dept.dev.team.m1.role": "Lead Développeur Full-Stack",
    "dept.dev.team.m1.desc": "Expert React, Node.js et architectures cloud avec plus de 10 ans d'expérience dans la conception de solutions scalables.",
    "dept.dev.team.m2.role": "Architecte Logiciel",
    "dept.dev.team.m2.desc": "Spécialiste des architectures microservices et des systèmes distribués haute disponibilité.",
    "dept.dev.team.m3.role": "Développeuse Mobile Senior",
    "dept.dev.team.m3.desc": "Experte React Native et Swift, passionnée par les interfaces fluides et les performances mobiles.",
    "dept.dev.team.m4.role": "Ingénieur DevOps",
    "dept.dev.team.m4.desc": "Maîtrise des pipelines CI/CD, Kubernetes et des infrastructures cloud AWS et GCP.",
    "dept.dev.cta.badge": "Passons à l'action",
    "dept.dev.cta.title": "Un projet de développement",
    "dept.dev.cta.titleHighlight": "en tête ?",
    "dept.dev.cta.subtitle": "Partagez-nous votre vision et notre équipe vous accompagnera de la conception à la mise en production.",
    "dept.dev.cta.button": "Lancer mon projet",
    "dept.dev.cta.secondary": "Voir nos réalisations",
    "dept.dev.overview.subtitle": "Découvrez notre approche unique du développement logiciel.",
    "dept.dev.services.subtitle": "De la conception à la mise en production, nous couvrons tous vos besoins.",
    "dept.dev.team.m1.name": "Alexandre Martin",
    "dept.dev.team.m2.name": "Sophie Bernard",
    "dept.dev.team.m3.name": "Claire Dubois",
    "dept.dev.team.m4.name": "Thomas Laurent",

    // Department Pages - Research
    "dept.research.hero.badge": "Département Recherches Innovantes",
    "dept.research.hero.title": "Repousser les frontières",
    "dept.research.hero.titleHighlight": "de l'innovation",
    "dept.research.hero.subtitle": "Nous explorons les technologies émergentes — IA, blockchain, IoT — pour concevoir les solutions de demain.",
    "dept.research.overview.badge": "Notre vision",
    "dept.research.overview.title": "La R&D au service",
    "dept.research.overview.titleHighlight": "de votre compétitivité",
    "dept.research.overview.text1": "Notre département de recherches innovantes est dédié à l'exploration des technologies de pointe. Nous transformons les avancées scientifiques en solutions concrètes et opérationnelles pour nos clients.",
    "dept.research.overview.text2": "De l'intelligence artificielle à la blockchain, en passant par l'IoT et l'automatisation, nous identifions les opportunités technologiques qui créent un avantage concurrentiel durable.",
    "dept.research.overview.stat1.value": "35+",
    "dept.research.overview.stat1.label": "Projets de R&D",
    "dept.research.overview.stat2.value": "8",
    "dept.research.overview.stat2.label": "Brevets déposés",
    "dept.research.overview.stat3.value": "15",
    "dept.research.overview.stat3.label": "Chercheurs & ingénieurs",
    "dept.research.services.badge": "Nos domaines",
    "dept.research.services.title": "Axes de recherche",
    "dept.research.services.titleHighlight": "& innovation",
    "dept.research.services.s1.title": "Intelligence Artificielle",
    "dept.research.services.s1.desc": "Modèles de machine learning, traitement du langage naturel et vision par ordinateur pour automatiser vos processus.",
    "dept.research.services.s2.title": "IA Générative",
    "dept.research.services.s2.desc": "Solutions basées sur les LLM pour la génération de contenu, l'assistance intelligente et l'analyse de données.",
    "dept.research.services.s3.title": "Blockchain & Web3",
    "dept.research.services.s3.desc": "Smart contracts, applications décentralisées et systèmes de traçabilité basés sur la blockchain.",
    "dept.research.services.s4.title": "IoT & Systèmes Embarqués",
    "dept.research.services.s4.desc": "Conception de systèmes connectés intelligents pour la collecte de données et le pilotage à distance.",
    "dept.research.services.s5.title": "Automatisation Intelligente",
    "dept.research.services.s5.desc": "Robots logiciels (RPA), workflows automatisés et orchestration de processus métier complexes.",
    "dept.research.services.s6.title": "Analyse Prédictive",
    "dept.research.services.s6.desc": "Modèles prédictifs et analytiques avancés pour anticiper les tendances et optimiser la prise de décision.",
    "dept.research.projects.badge": "Nos travaux",
    "dept.research.projects.title": "Projets de",
    "dept.research.projects.titleHighlight": "recherche",
    "dept.research.projects.current.p1.title": "Assistant IA CogniFlow",
    "dept.research.projects.current.p1.desc": "Agent conversationnel intelligent capable d'analyser des documents complexes et de fournir des synthèses contextuelles.",
    "dept.research.projects.current.p1.tag": "Intelligence Artificielle",
    "dept.research.projects.current.p2.title": "Plateforme IoT SmartField",
    "dept.research.projects.current.p2.desc": "Réseau de capteurs connectés pour l'agriculture de précision avec analyse prédictive des rendements.",
    "dept.research.projects.current.p2.tag": "IoT",
    "dept.research.projects.completed.p1.title": "ChainTrace Supply",
    "dept.research.projects.completed.p1.desc": "Système de traçabilité blockchain pour la chaîne d'approvisionnement avec vérification d'authenticité en temps réel.",
    "dept.research.projects.completed.p1.date": "Février 2026",
    "dept.research.projects.completed.p2.title": "AutoPilot RPA",
    "dept.research.projects.completed.p2.desc": "Suite d'automatisation robotisée des processus administratifs réduisant le temps de traitement de 75%.",
    "dept.research.projects.completed.p2.date": "Octobre 2025",
    "dept.research.projects.completed.p3.title": "VisionGuard AI",
    "dept.research.projects.completed.p3.desc": "Système de détection d'anomalies par vision par ordinateur pour le contrôle qualité industriel.",
    "dept.research.projects.completed.p3.date": "Juillet 2025",
    "dept.research.team.badge": "Notre équipe",
    "dept.research.team.title": "Les experts",
    "dept.research.team.titleHighlight": "recherche & innovation",
    "dept.research.team.m1.role": "Directeur R&D",
    "dept.research.team.m1.desc": "Docteur en informatique spécialisé en intelligence artificielle, 15 ans d'expérience en recherche appliquée.",
    "dept.research.team.m2.role": "Ingénieure Machine Learning",
    "dept.research.team.m2.desc": "Experte en deep learning et NLP, contributrice à plusieurs projets open source de référence.",
    "dept.research.team.m3.role": "Architecte Blockchain",
    "dept.research.team.m3.desc": "Spécialiste Ethereum et Solidity avec une expertise en conception de smart contracts sécurisés.",
    "dept.research.team.m4.role": "Ingénieur IoT",
    "dept.research.team.m4.desc": "Expert en systèmes embarqués et protocoles de communication pour objets connectés industriels.",
    "dept.research.cta.title": "Un défi technologique",
    "dept.research.cta.titleHighlight": "à relever ?",
    "dept.research.cta.subtitle": "Notre équipe R&D est prête à explorer avec vous les solutions innovantes qui feront la différence.",
    "dept.research.cta.button": "Explorer les possibilités",
    "dept.research.cta.badge": "Passons à l'action",
    "dept.research.cta.secondary": "Voir nos recherches",
    "dept.research.overview.subtitle": "Comprendre notre approche de la recherche et de l'innovation.",
    "dept.research.services.subtitle": "Nos domaines d'expertise en recherche et développement.",
    "dept.research.team.m1.name": "Marc Lefèvre",
    "dept.research.team.m2.name": "Julie Moreau",
    "dept.research.team.m3.name": "David Chen",
    "dept.research.team.m4.name": "Emma Petit",

    // Department Pages - Training
    "dept.training.hero.badge": "Département Formations",
    "dept.training.hero.title": "Développez les compétences",
    "dept.training.hero.titleHighlight": "de vos équipes",
    "dept.training.hero.subtitle": "Des formations professionnelles en développement web, data science et DevOps pour rester à la pointe de la technologie.",
    "dept.training.overview.badge": "Notre pédagogie",
    "dept.training.overview.title": "Apprendre en pratiquant",
    "dept.training.overview.titleHighlight": "pour mieux performer",
    "dept.training.overview.text1": "Notre département formations propose des programmes conçus par des professionnels en activité. Chaque formation allie théorie solide et mise en pratique immédiate sur des projets concrets.",
    "dept.training.overview.text2": "Que vous souhaitiez former vos équipes aux dernières technologies web, à la data science ou aux pratiques DevOps, nous adaptons nos programmes à votre contexte et vos objectifs.",
    "dept.training.overview.stat1.value": "500+",
    "dept.training.overview.stat1.label": "Professionnels formés",
    "dept.training.overview.stat2.value": "96%",
    "dept.training.overview.stat2.label": "Taux de satisfaction",
    "dept.training.overview.stat3.value": "20+",
    "dept.training.overview.stat3.label": "Programmes disponibles",
    "dept.training.services.badge": "Nos formations",
    "dept.training.services.title": "Programmes de",
    "dept.training.services.titleHighlight": "formation",
    "dept.training.services.s1.title": "Développement Web Frontend",
    "dept.training.services.s1.desc": "Maîtrisez React, Next.js et les frameworks modernes pour créer des interfaces performantes et accessibles.",
    "dept.training.services.s2.title": "Développement Backend & API",
    "dept.training.services.s2.desc": "Node.js, Python, architectures REST et GraphQL pour construire des backends robustes et scalables.",
    "dept.training.services.s3.title": "Data Science & IA",
    "dept.training.services.s3.desc": "Analyse de données, machine learning et deep learning avec Python, TensorFlow et les outils de l'écosystème data.",
    "dept.training.services.s4.title": "DevOps & Cloud",
    "dept.training.services.s4.desc": "Docker, Kubernetes, CI/CD et services cloud AWS/GCP pour des déploiements fiables et automatisés.",
    "dept.training.services.s5.title": "Workshops Intensifs",
    "dept.training.services.s5.desc": "Sessions pratiques d'une à deux journées sur des sujets ciblés : testing, sécurité, performance, accessibilité.",
    "dept.training.services.s6.title": "Coaching Technique",
    "dept.training.services.s6.desc": "Accompagnement personnalisé de vos équipes sur leurs projets réels avec revue de code et bonnes pratiques.",
    "dept.training.projects.badge": "Nos programmes",
    "dept.training.projects.title": "Formations",
    "dept.training.projects.titleHighlight": "récentes",
    "dept.training.projects.current.p1.title": "Bootcamp React Avancé",
    "dept.training.projects.current.p1.desc": "Programme intensif de 6 semaines couvrant React 19, Server Components, et les patterns d'architecture moderne.",
    "dept.training.projects.current.p1.tag": "Frontend",
    "dept.training.projects.current.p2.title": "Parcours Data Engineer",
    "dept.training.projects.current.p2.desc": "Formation complète de 8 semaines sur les pipelines de données, Spark, Airflow et les data warehouses cloud.",
    "dept.training.projects.current.p2.tag": "Data",
    "dept.training.projects.completed.p1.title": "Certification DevOps Pro",
    "dept.training.projects.completed.p1.desc": "Programme de certification couvrant Docker, Kubernetes, Terraform et les pipelines CI/CD en entreprise.",
    "dept.training.projects.completed.p1.date": "Mars 2026",
    "dept.training.projects.completed.p2.title": "Workshop Sécurité Web",
    "dept.training.projects.completed.p2.desc": "Formation intensive de 3 jours sur les vulnérabilités OWASP, les tests de pénétration et la sécurisation d'applications.",
    "dept.training.projects.completed.p2.date": "Décembre 2025",
    "dept.training.projects.completed.p3.title": "Formation IA pour Managers",
    "dept.training.projects.completed.p3.desc": "Programme de sensibilisation à l'IA et au machine learning destiné aux décideurs et chefs de projet.",
    "dept.training.projects.completed.p3.date": "Août 2025",
    "dept.training.team.badge": "Nos formateurs",
    "dept.training.team.title": "Les experts",
    "dept.training.team.titleHighlight": "formation",
    "dept.training.team.m1.role": "Responsable Pédagogique",
    "dept.training.team.m1.desc": "Ingénieure pédagogique avec 12 ans d'expérience dans la conception de parcours de formation technologiques.",
    "dept.training.team.m2.role": "Formateur Développement Web",
    "dept.training.team.m2.desc": "Développeur full-stack et formateur certifié, spécialiste React et Node.js avec une approche projet.",
    "dept.training.team.m3.role": "Formatrice Data Science",
    "dept.training.team.m3.desc": "Data scientist et enseignante, experte Python et machine learning, passionnée par la transmission des savoirs.",
    "dept.training.team.m4.role": "Formateur DevOps & Cloud",
    "dept.training.team.m4.desc": "Architecte cloud certifié AWS et GCP, spécialisé dans l'accompagnement d'équipes vers les pratiques DevOps.",
    "dept.training.cta.title": "Prêt à monter en",
    "dept.training.cta.titleHighlight": "compétences ?",
    "dept.training.cta.subtitle": "Contactez-nous pour construire un programme de formation adapté aux besoins de votre équipe.",
    "dept.training.cta.button": "Demander un programme",
    "dept.training.cta.badge": "Passons à l'action",
    "dept.training.cta.secondary": "Voir nos formations",
    "dept.training.overview.subtitle": "Notre philosophie de formation pour développer vos talents.",
    "dept.training.services.subtitle": "Des programmes complets pour monter en compétences.",
    "dept.training.team.m1.name": "Pierre Roux",
    "dept.training.team.m2.name": "Nathalie Simon",
    "dept.training.team.m3.name": "Karim Benali",
    "dept.training.team.m4.name": "Laura Fontaine",

    // Why Choose Us
    "why.badge": "Pourquoi nous choisir",
    "why.title": "L'expertise qui fait",
    "why.titleHighlight": "la différence",
    "why.subtitle": "Notre approche combine innovation technologique, expertise technique et solutions personnalisées pour chaque client.",
    "why.innovation.title": "Innovation",
    "why.innovation.desc": "Technologies de pointe et approches modernes pour des solutions toujours en avance sur leur temps.",
    "why.expertise.title": "Expertise Technique",
    "why.expertise.desc": "Une équipe de développeurs seniors maîtrisant les stacks les plus performantes du marché.",
    "why.tailored.title": "Solutions Sur Mesure",
    "why.tailored.desc": "Chaque projet est unique. Nous adaptons nos solutions à vos besoins spécifiques et à vos objectifs.",

    // Portfolio
    "portfolio.badge": "Nos réalisations",
    "portfolio.title": "Des projets qui",
    "portfolio.titleHighlight": "inspirent",
    "portfolio.subtitle": "Découvrez une sélection de nos projets récents qui illustrent notre savoir-faire et notre créativité.",
    "portfolio.project1.title": "E-Commerce Premium",
    "portfolio.project1.desc": "Plateforme e-commerce haute performance avec paiement intégré et gestion avancée des stocks.",
    "portfolio.project2.title": "Dashboard Analytics",
    "portfolio.project2.desc": "Application de visualisation de données en temps réel avec graphiques interactifs et rapports automatisés.",
    "portfolio.project3.title": "App Mobile Santé",
    "portfolio.project3.desc": "Application cross-platform de suivi de santé avec IA intégrée et synchronisation cloud.",
    "portfolio.project4.title": "Plateforme SaaS",
    "portfolio.project4.desc": "Solution SaaS B2B de gestion de projet avec collaboration en temps réel et automatisation des workflows.",
    "portfolio.viewProject": "Voir le projet",

    // Process
    "process.badge": "Notre processus",
    "process.title": "Une méthode",
    "process.titleHighlight": "éprouvée",
    "process.subtitle": "Un processus structuré en 4 étapes pour garantir le succès de chaque projet.",
    "process.step1.title": "Analyse",
    "process.step1.desc": "Compréhension approfondie de vos besoins, objectifs et contraintes. Audit technique et cahier des charges détaillé.",
    "process.step2.title": "Design",
    "process.step2.desc": "Création de maquettes et prototypes interactifs. Validation du design et de l'expérience utilisateur.",
    "process.step3.title": "Développement",
    "process.step3.desc": "Développement agile avec des sprints réguliers. Code propre, testé et documenté.",
    "process.step4.title": "Livraison",
    "process.step4.desc": "Déploiement, formation et support continu. Suivi des performances et optimisations.",

    // Stats
    "stats.projects": "Projets réalisés",
    "stats.satisfaction": "Satisfaction client",
    "stats.years": "Années d'expérience",
    "stats.technologies": "Technologies maîtrisées",

    // CTA
    "cta.title": "Prêt à transformer votre",
    "cta.titleHighlight": "projet digital ?",
    "cta.subtitle": "Discutons de votre projet et trouvons ensemble la meilleure solution pour atteindre vos objectifs.",
    "cta.button": "Démarrer votre projet",
    "cta.secondary": "Nous contacter",

    // Contact
    "contact.badge": "Contact",
    "contact.title": "Parlons de votre",
    "contact.titleHighlight": "projet",
    "contact.subtitle": "Vous avez un projet en tête ? Remplissez le formulaire ci-dessous et notre équipe vous recontactera dans les 24 heures.",
    "contact.form.name": "Nom complet",
    "contact.form.namePlaceholder": "Jean Dupont",
    "contact.form.emailPlaceholder": "jean@entreprise.com",
    "contact.form.phone": "Téléphone",
    "contact.form.phonePlaceholder": "+33 6 12 34 56 78",
    "contact.form.department": "Département",
    "contact.form.departmentPlaceholder": "Sélectionnez un département",
    "contact.form.subject": "Sujet",
    "contact.form.subjectPlaceholder": "En quoi pouvons-nous vous aider ?",
    "contact.form.messagePlaceholder": "Décrivez votre projet, vos besoins, vos délais...",
    "contact.form.submit": "Envoyer le message",
    "contact.success.title": "Message envoyé !",
    "contact.success.desc": "Merci pour votre message. Notre équipe vous recontactera dans les plus brefs délais.",
    "contact.success.another": "Envoyer un autre message",

    // Footer
    "footer.desc": "Agence digitale spécialisée dans la conception et le développement de solutions web innovantes et performantes.",
    "footer.navigation": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "footer.legal": "Mentions légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.dev": "Développement",
    "footer.research": "Recherches Innovantes",
    "footer.training": "Formations",
    "footer.newsletterDesc": "Recevez nos dernières actualités et articles directement dans votre boîte mail.",

    // Legal - Mentions légales
    "legal.back": "Retour à l'accueil",
    "legal.title": "Mentions légales",
    "legal.lastUpdated": "Dernière mise à jour : 1er janvier 2026",
    "legal.editor.title": "Éditeur du site",
    "legal.editor.content": "Le site alopro.com est édité par ALOPRO SAS, société par actions simplifiée au capital de 10 000 euros.\n\nSiège social : 123 Avenue de l'Innovation, 75008 Paris, France\nSIRET : 123 456 789 00012\nDirecteur de la publication : Jean Dupont\nEmail : contact@alopro.com\nTéléphone : +33 1 23 45 67 89",
    "legal.hosting.title": "Hébergement",
    "legal.hosting.content": "Le site est hébergé par Vercel Inc.\nAdresse : 340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis\nSite web : https://vercel.com",
    "legal.ip.title": "Propriété intellectuelle",
    "legal.ip.content": "L'ensemble du contenu du site (textes, images, vidéos, logos, icônes, sons, logiciels, etc.) est protégé par le droit de la propriété intellectuelle. Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable d'ALOPRO SAS.",
    "legal.liability.title": "Limitation de responsabilité",
    "legal.liability.content": "ALOPRO SAS ne saurait être tenue responsable des dommages directs ou indirects causés au matériel de l'utilisateur lors de l'accès au site. ALOPRO SAS décline toute responsabilité quant à l'utilisation qui pourrait être faite des informations et contenus présents sur le site.",
    "legal.data.title": "Données personnelles",
    "legal.data.content": "Conformément au Règlement Général sur la Protection des Données (RGPD) et à la loi Informatique et Libertés, vous disposez d'un droit d'accès, de rectification, de suppression et d'opposition aux données personnelles vous concernant. Pour exercer ces droits, vous pouvez nous contacter à l'adresse : contact@alopro.com",
    "legal.cookies.title": "Cookies",
    "legal.cookies.content": "Le site peut être amené à utiliser des cookies pour améliorer l'expérience utilisateur et réaliser des statistiques de visite. L'utilisateur peut configurer son navigateur pour refuser les cookies. Cependant, certaines fonctionnalités du site pourraient ne plus être accessibles.",
    "legal.law.title": "Droit applicable",
    "legal.law.content": "Les présentes mentions légales sont régies par le droit français. En cas de litige, les tribunaux de Paris seront seuls compétents.",

    // Privacy - Politique de confidentialité
    "privacy.back": "Retour à l'accueil",
    "privacy.title": "Politique de confidentialité",
    "privacy.lastUpdated": "Dernière mise à jour : 1er janvier 2026",
    "privacy.intro.title": "Introduction",
    "privacy.intro.content": "ALOPRO SAS, soucieuse des droits des individus, notamment au regard des traitements automatisés, et dans une volonté de transparence, a mis en place une politique reprenant l'ensemble de ces traitements, des finalités poursuivies ainsi que des moyens d'actions à la disposition des individus afin qu'ils puissent au mieux exercer leurs droits. Pour toute information complémentaire, vous pouvez nous contacter à : contact@alopro.com",
    "privacy.collected.title": "Données collectées",
    "privacy.collected.content": "Dans le cadre de l'utilisation de notre site, nous sommes susceptibles de collecter les catégories de données suivantes :",
    "privacy.collected.item1": "Données d'identification : nom, prénom, adresse email, numéro de téléphone",
    "privacy.collected.item2": "Données de connexion : adresse IP, logs de connexion, type de navigateur",
    "privacy.collected.item3": "Données de navigation : pages consultées, durée de visite, parcours sur le site",
    "privacy.collected.item4": "Données relatives aux demandes de contact : objet et contenu des messages",
    "privacy.purpose.title": "Finalité du traitement",
    "privacy.purpose.content": "Les données collectées sont utilisées pour les finalités suivantes :",
    "privacy.purpose.item1": "Répondre à vos demandes de contact et de devis",
    "privacy.purpose.item2": "Améliorer nos services et l'expérience utilisateur sur le site",
    "privacy.purpose.item3": "Réaliser des statistiques de fréquentation anonymisées",
    "privacy.retention.title": "Durée de conservation",
    "privacy.retention.content": "Les données personnelles sont conservées pour une durée n'excédant pas celle nécessaire au regard des finalités pour lesquelles elles sont traitées. Les données de contact sont conservées pendant 3 ans à compter du dernier échange. Les données de navigation sont conservées pendant 13 mois conformément aux recommandations de la CNIL.",
    "privacy.rights.title": "Droits des utilisateurs",
    "privacy.rights.content": "Conformément au RGPD, vous disposez des droits suivants concernant vos données personnelles :",
    "privacy.rights.item1": "Droit d'accès : obtenir la confirmation du traitement de vos données et en recevoir une copie",
    "privacy.rights.item2": "Droit de rectification : demander la correction de données inexactes",
    "privacy.rights.item3": "Droit à l'effacement : demander la suppression de vos données",
    "privacy.rights.item4": "Droit à la portabilité : recevoir vos données dans un format structuré",
    "privacy.rights.item5": "Droit d'opposition : vous opposer au traitement de vos données",
    "privacy.security.title": "Sécurité des données",
    "privacy.security.content": "ALOPRO SAS met en œuvre des mesures techniques et organisationnelles appropriées afin de garantir un niveau de sécurité adapté au risque. Nous utilisons des protocoles de chiffrement pour la transmission de données et des systèmes de protection contre les accès non autorisés.",
    "privacy.dpo.title": "Contact DPO",
    "privacy.dpo.content": "Pour toute question relative à la protection de vos données personnelles ou pour exercer vos droits, vous pouvez contacter notre Délégué à la Protection des Données :\n\nJean Dupont — DPO\nALOPRO SAS\n123 Avenue de l'Innovation, 75008 Paris, France\nEmail : contact@alopro.com",
  },
  en: {
    // Nav
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.cta": "Start a project",
    "nav.menu": "Menu",

    // Hero
    "hero.badge": "Innovative digital agency",
    "hero.titleLine1": "We bring your",
    "hero.titleHighlight": "digital projects",
    "hero.titleLine2": "to life with precision.",
    "hero.subtitle": "Development, research and training — three areas of expertise serving your digital ambition.",
    "hero.cta1": "Start a project",
    "hero.cta2": "Discover our services",

    // Services - Departments
    "services.badge": "Our departments",
    "services.title": "Three centers of expertise",
    "services.titleHighlight": "serving your vision",
    "services.subtitle": "Our company is structured around three complementary departments to meet all your digital needs.",

    "services.dev.title": "Development Department",
    "services.dev.desc": "Design and delivery of custom digital solutions, from showcase websites to complex software.",
    "services.dev.tag": "Development",
    "services.dev.item1": "Showcase & e-commerce websites",
    "services.dev.item2": "Web & mobile applications",
    "services.dev.item3": "Custom business software",
    "services.dev.item4": "APIs & integrations",

    "services.research.title": "Innovative Research Department",
    "services.research.desc": "Exploring emerging technologies and developing cutting-edge solutions to anticipate tomorrow's needs.",
    "services.research.tag": "R&D",
    "services.research.item1": "Artificial intelligence & generative AI",
    "services.research.item2": "Intelligent automation",
    "services.research.item3": "Blockchain & Web3",
    "services.research.item4": "IoT & embedded systems",

    "services.training.title": "Training Department",
    "services.training.desc": "Professional training programs to support your teams' skills development on modern technologies.",
    "services.training.tag": "Training",
    "services.training.item1": "Web & mobile development",
    "services.training.item2": "Data Science & AI",
    "services.training.item3": "DevOps & Cloud",
    "services.training.item4": "Workshops & technical coaching",

    "services.cta.text": "Have a project in mind?",
    "services.cta.sub": "Let's talk and build together the solution tailored to your ambitions.",
    "services.cta.button": "Let's discuss your project",

    // Department Pages - Shared
    "dept.backHome": "Back to home",
    "dept.currentProjects": "Current projects",
    "dept.completedProjects": "Completed projects",
    "dept.inProgress": "In progress",
    "dept.completed": "Completed",
    "dept.teamExpertise": "Team expertise",
    "dept.learnMore": "Learn more",
    "dept.overview": "Overview",

    // Department Pages - Dev
    "dept.dev.hero.badge": "Development Department",
    "dept.dev.hero.title": "Custom digital",
    "dept.dev.hero.titleHighlight": "solutions",
    "dept.dev.hero.subtitle": "We design and develop websites, mobile applications and custom software that propel your business forward.",
    "dept.dev.overview.badge": "Our approach",
    "dept.dev.overview.title": "Technical excellence",
    "dept.dev.overview.titleHighlight": "at the heart of every project",
    "dept.dev.overview.text1": "Our development department brings together experts passionate about creating high-performance digital solutions. From showcase websites to complex business applications, we master the entire production chain.",
    "dept.dev.overview.text2": "We adopt agile methodologies and the latest technologies to ensure quality, maintainable and scalable deliverables.",
    "dept.dev.overview.stat1.value": "150+",
    "dept.dev.overview.stat1.label": "Projects delivered",
    "dept.dev.overview.stat2.value": "98%",
    "dept.dev.overview.stat2.label": "Satisfied clients",
    "dept.dev.overview.stat3.value": "12",
    "dept.dev.overview.stat3.label": "Senior developers",
    "dept.dev.services.badge": "Our services",
    "dept.dev.services.title": "Comprehensive development",
    "dept.dev.services.titleHighlight": "solutions",
    "dept.dev.services.s1.title": "Showcase Websites",
    "dept.dev.services.s1.desc": "Modern, responsive and SEO-optimized websites to strengthen your online presence and attract new clients.",
    "dept.dev.services.s2.title": "E-Commerce",
    "dept.dev.services.s2.desc": "High-performance online stores with inventory management, secure payments and optimized shopping experience.",
    "dept.dev.services.s3.title": "Web Applications",
    "dept.dev.services.s3.desc": "Custom web applications with intuitive interfaces, dashboards and advanced business features.",
    "dept.dev.services.s4.title": "Mobile Applications",
    "dept.dev.services.s4.desc": "Native or cross-platform iOS and Android applications to reach your users wherever they are.",
    "dept.dev.services.s5.title": "Custom Software",
    "dept.dev.services.s5.desc": "Custom business software development to automate and optimize your internal processes.",
    "dept.dev.services.s6.title": "APIs & Integrations",
    "dept.dev.services.s6.desc": "Design of robust APIs and third-party service integration to connect your systems together.",
    "dept.dev.projects.badge": "Our work",
    "dept.dev.projects.title": "Development",
    "dept.dev.projects.titleHighlight": "projects",
    "dept.dev.projects.current.p1.title": "NeoBank Client Portal",
    "dept.dev.projects.current.p1.desc": "Online banking platform with interactive dashboard, multi-account management and real-time notifications.",
    "dept.dev.projects.current.p1.tag": "Web Application",
    "dept.dev.projects.current.p2.title": "FitTrack Mobile App",
    "dept.dev.projects.current.p2.desc": "Sports tracking application with personalized training plans, statistics and connected device integration.",
    "dept.dev.projects.current.p2.tag": "Mobile",
    "dept.dev.projects.completed.p1.title": "ArtisanConnect Marketplace",
    "dept.dev.projects.completed.p1.desc": "Marketplace connecting local artisans with customers, featuring integrated booking and payment systems.",
    "dept.dev.projects.completed.p1.date": "January 2026",
    "dept.dev.projects.completed.p2.title": "LogiFlow ERP",
    "dept.dev.projects.completed.p2.desc": "Integrated management software for SMEs covering invoicing, inventory and customer relationship management.",
    "dept.dev.projects.completed.p2.date": "November 2025",
    "dept.dev.projects.completed.p3.title": "GreenLeaf E-Commerce",
    "dept.dev.projects.completed.p3.desc": "Organic products online store with basket configurator, subscriptions and scheduled delivery.",
    "dept.dev.projects.completed.p3.date": "September 2025",
    "dept.dev.team.badge": "Our team",
    "dept.dev.team.title": "The development",
    "dept.dev.team.titleHighlight": "experts",
    "dept.dev.team.m1.role": "Lead Full-Stack Developer",
    "dept.dev.team.m1.desc": "React, Node.js and cloud architecture expert with over 10 years of experience designing scalable solutions.",
    "dept.dev.team.m2.role": "Software Architect",
    "dept.dev.team.m2.desc": "Specialist in microservices architectures and high-availability distributed systems.",
    "dept.dev.team.m3.role": "Senior Mobile Developer",
    "dept.dev.team.m3.desc": "React Native and Swift expert, passionate about fluid interfaces and mobile performance.",
    "dept.dev.team.m4.role": "DevOps Engineer",
    "dept.dev.team.m4.desc": "Proficient in CI/CD pipelines, Kubernetes and AWS/GCP cloud infrastructures.",
    "dept.dev.cta.title": "Have a development project",
    "dept.dev.cta.titleHighlight": "in mind?",
    "dept.dev.cta.subtitle": "Share your vision with us and our team will guide you from design to production deployment.",
    "dept.dev.cta.button": "Launch my project",
    "dept.dev.cta.badge": "Let's take action",
    "dept.dev.cta.secondary": "See our work",
    "dept.dev.overview.subtitle": "Discover our unique approach to software development.",
    "dept.dev.services.subtitle": "From design to production, we cover all your needs.",
    "dept.dev.team.m1.name": "Alexandre Martin",
    "dept.dev.team.m2.name": "Sophie Bernard",
    "dept.dev.team.m3.name": "Claire Dubois",
    "dept.dev.team.m4.name": "Thomas Laurent",

    // Department Pages - Research
    "dept.research.hero.badge": "Innovative Research Department",
    "dept.research.hero.title": "Pushing the boundaries",
    "dept.research.hero.titleHighlight": "of innovation",
    "dept.research.hero.subtitle": "We explore emerging technologies — AI, blockchain, IoT — to design tomorrow's solutions.",
    "dept.research.overview.badge": "Our vision",
    "dept.research.overview.title": "R&D serving",
    "dept.research.overview.titleHighlight": "your competitiveness",
    "dept.research.overview.text1": "Our innovative research department is dedicated to exploring cutting-edge technologies. We transform scientific advances into concrete, operational solutions for our clients.",
    "dept.research.overview.text2": "From artificial intelligence to blockchain, through IoT and automation, we identify technological opportunities that create a lasting competitive advantage.",
    "dept.research.overview.stat1.value": "35+",
    "dept.research.overview.stat1.label": "R&D projects",
    "dept.research.overview.stat2.value": "8",
    "dept.research.overview.stat2.label": "Patents filed",
    "dept.research.overview.stat3.value": "15",
    "dept.research.overview.stat3.label": "Researchers & engineers",
    "dept.research.services.badge": "Our domains",
    "dept.research.services.title": "Research areas",
    "dept.research.services.titleHighlight": "& innovation",
    "dept.research.services.s1.title": "Artificial Intelligence",
    "dept.research.services.s1.desc": "Machine learning models, natural language processing and computer vision to automate your processes.",
    "dept.research.services.s2.title": "Generative AI",
    "dept.research.services.s2.desc": "LLM-based solutions for content generation, intelligent assistance and data analysis.",
    "dept.research.services.s3.title": "Blockchain & Web3",
    "dept.research.services.s3.desc": "Smart contracts, decentralized applications and blockchain-based traceability systems.",
    "dept.research.services.s4.title": "IoT & Embedded Systems",
    "dept.research.services.s4.desc": "Design of intelligent connected systems for data collection and remote monitoring.",
    "dept.research.services.s5.title": "Intelligent Automation",
    "dept.research.services.s5.desc": "Software robots (RPA), automated workflows and complex business process orchestration.",
    "dept.research.services.s6.title": "Predictive Analytics",
    "dept.research.services.s6.desc": "Advanced predictive and analytical models to anticipate trends and optimize decision-making.",
    "dept.research.projects.badge": "Our work",
    "dept.research.projects.title": "Research",
    "dept.research.projects.titleHighlight": "projects",
    "dept.research.projects.current.p1.title": "CogniFlow AI Assistant",
    "dept.research.projects.current.p1.desc": "Intelligent conversational agent capable of analyzing complex documents and providing contextual summaries.",
    "dept.research.projects.current.p1.tag": "Artificial Intelligence",
    "dept.research.projects.current.p2.title": "SmartField IoT Platform",
    "dept.research.projects.current.p2.desc": "Connected sensor network for precision agriculture with predictive yield analysis.",
    "dept.research.projects.current.p2.tag": "IoT",
    "dept.research.projects.completed.p1.title": "ChainTrace Supply",
    "dept.research.projects.completed.p1.desc": "Blockchain traceability system for the supply chain with real-time authenticity verification.",
    "dept.research.projects.completed.p1.date": "February 2026",
    "dept.research.projects.completed.p2.title": "AutoPilot RPA",
    "dept.research.projects.completed.p2.desc": "Robotic process automation suite for administrative tasks reducing processing time by 75%.",
    "dept.research.projects.completed.p2.date": "October 2025",
    "dept.research.projects.completed.p3.title": "VisionGuard AI",
    "dept.research.projects.completed.p3.desc": "Computer vision anomaly detection system for industrial quality control.",
    "dept.research.projects.completed.p3.date": "July 2025",
    "dept.research.team.badge": "Our team",
    "dept.research.team.title": "The research",
    "dept.research.team.titleHighlight": "& innovation experts",
    "dept.research.team.m1.role": "R&D Director",
    "dept.research.team.m1.desc": "PhD in computer science specialized in artificial intelligence, 15 years of experience in applied research.",
    "dept.research.team.m2.role": "Machine Learning Engineer",
    "dept.research.team.m2.desc": "Deep learning and NLP expert, contributor to several leading open source projects.",
    "dept.research.team.m3.role": "Blockchain Architect",
    "dept.research.team.m3.desc": "Ethereum and Solidity specialist with expertise in secure smart contract design.",
    "dept.research.team.m4.role": "IoT Engineer",
    "dept.research.team.m4.desc": "Expert in embedded systems and communication protocols for industrial connected devices.",
    "dept.research.cta.title": "A technological challenge",
    "dept.research.cta.titleHighlight": "to tackle?",
    "dept.research.cta.subtitle": "Our R&D team is ready to explore innovative solutions with you that will make the difference.",
    "dept.research.cta.button": "Explore the possibilities",
    "dept.research.cta.badge": "Let's take action",
    "dept.research.cta.secondary": "See our research",
    "dept.research.overview.subtitle": "Understand our approach to research and innovation.",
    "dept.research.services.subtitle": "Our areas of expertise in research and development.",
    "dept.research.team.m1.name": "Marc Lefèvre",
    "dept.research.team.m2.name": "Julie Moreau",
    "dept.research.team.m3.name": "David Chen",
    "dept.research.team.m4.name": "Emma Petit",

    // Department Pages - Training
    "dept.training.hero.badge": "Training Department",
    "dept.training.hero.title": "Develop your team's",
    "dept.training.hero.titleHighlight": "skills",
    "dept.training.hero.subtitle": "Professional training in web development, data science and DevOps to stay at the forefront of technology.",
    "dept.training.overview.badge": "Our pedagogy",
    "dept.training.overview.title": "Learn by doing",
    "dept.training.overview.titleHighlight": "to perform better",
    "dept.training.overview.text1": "Our training department offers programs designed by active professionals. Each course combines solid theory with hands-on practice on real projects.",
    "dept.training.overview.text2": "Whether you want to train your teams on the latest web technologies, data science or DevOps practices, we tailor our programs to your context and goals.",
    "dept.training.overview.stat1.value": "500+",
    "dept.training.overview.stat1.label": "Professionals trained",
    "dept.training.overview.stat2.value": "96%",
    "dept.training.overview.stat2.label": "Satisfaction rate",
    "dept.training.overview.stat3.value": "20+",
    "dept.training.overview.stat3.label": "Programs available",
    "dept.training.services.badge": "Our courses",
    "dept.training.services.title": "Training",
    "dept.training.services.titleHighlight": "programs",
    "dept.training.services.s1.title": "Frontend Web Development",
    "dept.training.services.s1.desc": "Master React, Next.js and modern frameworks to create performant and accessible interfaces.",
    "dept.training.services.s2.title": "Backend Development & APIs",
    "dept.training.services.s2.desc": "Node.js, Python, REST and GraphQL architectures to build robust and scalable backends.",
    "dept.training.services.s3.title": "Data Science & AI",
    "dept.training.services.s3.desc": "Data analysis, machine learning and deep learning with Python, TensorFlow and the data ecosystem tools.",
    "dept.training.services.s4.title": "DevOps & Cloud",
    "dept.training.services.s4.desc": "Docker, Kubernetes, CI/CD and AWS/GCP cloud services for reliable and automated deployments.",
    "dept.training.services.s5.title": "Intensive Workshops",
    "dept.training.services.s5.desc": "One to two-day practical sessions on targeted topics: testing, security, performance, accessibility.",
    "dept.training.services.s6.title": "Technical Coaching",
    "dept.training.services.s6.desc": "Personalized support for your teams on real projects with code review and best practices.",
    "dept.training.projects.badge": "Our programs",
    "dept.training.projects.title": "Recent",
    "dept.training.projects.titleHighlight": "training courses",
    "dept.training.projects.current.p1.title": "Advanced React Bootcamp",
    "dept.training.projects.current.p1.desc": "Intensive 6-week program covering React 19, Server Components, and modern architecture patterns.",
    "dept.training.projects.current.p1.tag": "Frontend",
    "dept.training.projects.current.p2.title": "Data Engineer Path",
    "dept.training.projects.current.p2.desc": "Comprehensive 8-week course on data pipelines, Spark, Airflow and cloud data warehouses.",
    "dept.training.projects.current.p2.tag": "Data",
    "dept.training.projects.completed.p1.title": "DevOps Pro Certification",
    "dept.training.projects.completed.p1.desc": "Certification program covering Docker, Kubernetes, Terraform and enterprise CI/CD pipelines.",
    "dept.training.projects.completed.p1.date": "March 2026",
    "dept.training.projects.completed.p2.title": "Web Security Workshop",
    "dept.training.projects.completed.p2.desc": "Intensive 3-day training on OWASP vulnerabilities, penetration testing and application security.",
    "dept.training.projects.completed.p2.date": "December 2025",
    "dept.training.projects.completed.p3.title": "AI for Managers Training",
    "dept.training.projects.completed.p3.desc": "AI and machine learning awareness program designed for decision-makers and project managers.",
    "dept.training.projects.completed.p3.date": "August 2025",
    "dept.training.team.badge": "Our trainers",
    "dept.training.team.title": "The training",
    "dept.training.team.titleHighlight": "experts",
    "dept.training.team.m1.role": "Head of Training",
    "dept.training.team.m1.desc": "Instructional engineer with 12 years of experience designing technology training programs.",
    "dept.training.team.m2.role": "Web Development Trainer",
    "dept.training.team.m2.desc": "Full-stack developer and certified trainer, React and Node.js specialist with a project-based approach.",
    "dept.training.team.m3.role": "Data Science Trainer",
    "dept.training.team.m3.desc": "Data scientist and educator, Python and machine learning expert, passionate about knowledge sharing.",
    "dept.training.team.m4.role": "DevOps & Cloud Trainer",
    "dept.training.team.m4.desc": "AWS and GCP certified cloud architect, specialized in guiding teams toward DevOps practices.",
    "dept.training.cta.title": "Ready to level up",
    "dept.training.cta.titleHighlight": "your skills?",
    "dept.training.cta.subtitle": "Contact us to build a training program tailored to your team's needs.",
    "dept.training.cta.button": "Request a program",
    "dept.training.cta.badge": "Let's take action",
    "dept.training.cta.secondary": "See our programs",
    "dept.training.overview.subtitle": "Our training philosophy to develop your talent.",
    "dept.training.services.subtitle": "Comprehensive programs to level up your skills.",
    "dept.training.team.m1.name": "Pierre Roux",
    "dept.training.team.m2.name": "Nathalie Simon",
    "dept.training.team.m3.name": "Karim Benali",
    "dept.training.team.m4.name": "Laura Fontaine",

    // Why Choose Us
    "why.badge": "Why choose us",
    "why.title": "The expertise that makes",
    "why.titleHighlight": "the difference",
    "why.subtitle": "Our approach combines technological innovation, technical expertise and personalized solutions for each client.",
    "why.innovation.title": "Innovation",
    "why.innovation.desc": "Cutting-edge technologies and modern approaches for solutions always ahead of their time.",
    "why.expertise.title": "Technical Expertise",
    "why.expertise.desc": "A team of senior developers mastering the most powerful stacks on the market.",
    "why.tailored.title": "Tailored Solutions",
    "why.tailored.desc": "Every project is unique. We adapt our solutions to your specific needs and objectives.",

    // Portfolio
    "portfolio.badge": "Our work",
    "portfolio.title": "Projects that",
    "portfolio.titleHighlight": "inspire",
    "portfolio.subtitle": "Discover a selection of our recent projects that showcase our expertise and creativity.",
    "portfolio.project1.title": "Premium E-Commerce",
    "portfolio.project1.desc": "High-performance e-commerce platform with integrated payments and advanced inventory management.",
    "portfolio.project2.title": "Analytics Dashboard",
    "portfolio.project2.desc": "Real-time data visualization application with interactive charts and automated reporting.",
    "portfolio.project3.title": "Health Mobile App",
    "portfolio.project3.desc": "Cross-platform health tracking application with integrated AI and cloud synchronization.",
    "portfolio.project4.title": "SaaS Platform",
    "portfolio.project4.desc": "B2B SaaS project management solution with real-time collaboration and workflow automation.",
    "portfolio.viewProject": "View project",

    // Process
    "process.badge": "Our process",
    "process.title": "A proven",
    "process.titleHighlight": "methodology",
    "process.subtitle": "A structured 4-step process to ensure the success of every project.",
    "process.step1.title": "Analysis",
    "process.step1.desc": "Deep understanding of your needs, goals and constraints. Technical audit and detailed specifications.",
    "process.step2.title": "Design",
    "process.step2.desc": "Creation of interactive mockups and prototypes. Design and user experience validation.",
    "process.step3.title": "Development",
    "process.step3.desc": "Agile development with regular sprints. Clean, tested and documented code.",
    "process.step4.title": "Delivery",
    "process.step4.desc": "Deployment, training and ongoing support. Performance monitoring and optimizations.",

    // Stats
    "stats.projects": "Projects completed",
    "stats.satisfaction": "Client satisfaction",
    "stats.years": "Years of experience",
    "stats.technologies": "Technologies mastered",

    // CTA
    "cta.title": "Ready to transform your",
    "cta.titleHighlight": "digital project?",
    "cta.subtitle": "Let's discuss your project and find the best solution together to achieve your goals.",
    "cta.button": "Start your project",
    "cta.secondary": "Contact us",

    // Contact
    "contact.badge": "Contact",
    "contact.title": "Let's talk about your",
    "contact.titleHighlight": "project",
    "contact.subtitle": "Have a project in mind? Fill out the form below and our team will get back to you within 24 hours.",
    "contact.form.name": "Full name",
    "contact.form.namePlaceholder": "John Doe",
    "contact.form.emailPlaceholder": "john@company.com",
    "contact.form.phone": "Phone",
    "contact.form.phonePlaceholder": "+33 6 12 34 56 78",
    "contact.form.department": "Department",
    "contact.form.departmentPlaceholder": "Select a department",
    "contact.form.subject": "Subject",
    "contact.form.subjectPlaceholder": "How can we help you?",
    "contact.form.messagePlaceholder": "Describe your project, needs, timeline...",
    "contact.form.submit": "Send message",
    "contact.success.title": "Message sent!",
    "contact.success.desc": "Thank you for your message. Our team will get back to you as soon as possible.",
    "contact.success.another": "Send another message",

    // Footer
    "footer.desc": "Digital agency specializing in the design and development of innovative and high-performance web solutions.",
    "footer.navigation": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.legal": "Legal notice",
    "footer.privacy": "Privacy policy",
    "footer.dev": "Development",
    "footer.research": "Innovative Research",
    "footer.training": "Training",
    "footer.newsletterDesc": "Get our latest news and articles delivered straight to your inbox.",

    // Legal - Legal Notice
    "legal.back": "Back to home",
    "legal.title": "Legal Notice",
    "legal.lastUpdated": "Last updated: January 1, 2026",
    "legal.editor.title": "Site Publisher",
    "legal.editor.content": "The website alopro.com is published by ALOPRO SAS, a simplified joint-stock company with a share capital of 10,000 euros.\n\nRegistered office: 123 Avenue de l'Innovation, 75008 Paris, France\nSIRET: 123 456 789 00012\nPublication director: Jean Dupont\nEmail: contact@alopro.com\nPhone: +33 1 23 45 67 89",
    "legal.hosting.title": "Hosting",
    "legal.hosting.content": "The site is hosted by Vercel Inc.\nAddress: 340 S Lemon Ave #4133, Walnut, CA 91789, United States\nWebsite: https://vercel.com",
    "legal.ip.title": "Intellectual Property",
    "legal.ip.content": "All content on this site (texts, images, videos, logos, icons, sounds, software, etc.) is protected by intellectual property law. Any reproduction, representation, modification, publication, or adaptation of all or part of the elements of the site, by any means or process, is prohibited without prior written authorization from ALOPRO SAS.",
    "legal.liability.title": "Limitation of Liability",
    "legal.liability.content": "ALOPRO SAS cannot be held responsible for direct or indirect damage caused to the user's equipment when accessing the site. ALOPRO SAS disclaims all liability for the use that may be made of the information and content on the site.",
    "legal.data.title": "Personal Data",
    "legal.data.content": "In accordance with the General Data Protection Regulation (GDPR) and the French Data Protection Act, you have the right to access, rectify, delete, and object to personal data concerning you. To exercise these rights, you may contact us at: contact@alopro.com",
    "legal.cookies.title": "Cookies",
    "legal.cookies.content": "The site may use cookies to improve the user experience and compile visitor statistics. Users can configure their browser to refuse cookies. However, some features of the site may no longer be accessible.",
    "legal.law.title": "Applicable Law",
    "legal.law.content": "These legal notices are governed by French law. In the event of a dispute, the courts of Paris shall have exclusive jurisdiction.",

    // Privacy - Privacy Policy
    "privacy.back": "Back to home",
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated: January 1, 2026",
    "privacy.intro.title": "Introduction",
    "privacy.intro.content": "ALOPRO SAS, concerned about the rights of individuals, particularly with regard to automated processing, and in a spirit of transparency, has established a policy covering all such processing, the purposes pursued, and the means of action available to individuals so that they may best exercise their rights. For any additional information, you may contact us at: contact@alopro.com",
    "privacy.collected.title": "Data Collected",
    "privacy.collected.content": "In the course of using our site, we may collect the following categories of data:",
    "privacy.collected.item1": "Identification data: last name, first name, email address, phone number",
    "privacy.collected.item2": "Connection data: IP address, connection logs, browser type",
    "privacy.collected.item3": "Browsing data: pages viewed, visit duration, site navigation path",
    "privacy.collected.item4": "Contact request data: subject and content of messages",
    "privacy.purpose.title": "Purpose of Processing",
    "privacy.purpose.content": "The data collected is used for the following purposes:",
    "privacy.purpose.item1": "Responding to your contact and quote requests",
    "privacy.purpose.item2": "Improving our services and user experience on the site",
    "privacy.purpose.item3": "Compiling anonymized traffic statistics",
    "privacy.retention.title": "Data Retention Period",
    "privacy.retention.content": "Personal data is retained for a period not exceeding that necessary for the purposes for which it is processed. Contact data is retained for 3 years from the last exchange. Browsing data is retained for 13 months in accordance with CNIL recommendations.",
    "privacy.rights.title": "User Rights",
    "privacy.rights.content": "In accordance with the GDPR, you have the following rights regarding your personal data:",
    "privacy.rights.item1": "Right of access: obtain confirmation of the processing of your data and receive a copy",
    "privacy.rights.item2": "Right of rectification: request the correction of inaccurate data",
    "privacy.rights.item3": "Right to erasure: request the deletion of your data",
    "privacy.rights.item4": "Right to data portability: receive your data in a structured format",
    "privacy.rights.item5": "Right to object: object to the processing of your data",
    "privacy.security.title": "Data Security",
    "privacy.security.content": "ALOPRO SAS implements appropriate technical and organizational measures to ensure a level of security appropriate to the risk. We use encryption protocols for data transmission and systems to protect against unauthorized access.",
    "privacy.dpo.title": "DPO Contact",
    "privacy.dpo.content": "For any questions regarding the protection of your personal data or to exercise your rights, you may contact our Data Protection Officer:\n\nJean Dupont — DPO\nALOPRO SAS\n123 Avenue de l'Innovation, 75008 Paris, France\nEmail: contact@alopro.com",
  },
};

// --- locale store (external store for useSyncExternalStore) ---
let listeners: Array<() => void> = [];
let currentLocale: Locale = "en";

function getLocaleSnapshot(): Locale {
  return currentLocale;
}

function getLocaleServerSnapshot(): Locale {
  return "en";
}

function subscribeLocale(listener: () => void) {
  listeners.push(listener);
  return () => {
    listeners = listeners.filter((l) => l !== listener);
  };
}

function setLocaleStore(newLocale: Locale) {
  currentLocale = newLocale;
  localStorage.setItem("locale", newLocale);
  listeners.forEach((l) => l());
}

// Init on client: read stored or detect browser lang
if (typeof window !== "undefined") {
  const stored = localStorage.getItem("locale");
  if (stored === "fr" || stored === "en") {
    currentLocale = stored;
  } else {
    const browserLang = navigator.language || "";
    currentLocale = browserLang.startsWith("fr") ? "fr" : "en";
    localStorage.setItem("locale", currentLocale);
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const locale = useSyncExternalStore(subscribeLocale, getLocaleSnapshot, getLocaleServerSnapshot);

  const setLocale = useCallback((newLocale: Locale) => {
    setLocaleStore(newLocale);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[locale][key] ?? key;
  }, [locale]);

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
